server:
  servlet:
    context-path: /wp-json/zhixin
  port: 8100

  ssl:
    key-store: D:\httpsKey.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: anyname
spring:

  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/words?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 从连接池返回的连接的自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活，默认1800000（30分钟）
      max-lifetime: 1800000
      # 连接超时时间，默认30000（30秒）
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

#  redis:
#    host: 127.0.0.1
#    port: 6379
#    #默认数据库
#    database: 0
#    timeout: 10000ms
#    lettuce:
#      pool:
#        max-active: 100
#        max-wait: 10000ms
#        #最大空闲连接数
#        max-idle: 200
#        min-idle: 0
# Mybatis-plus配置
mybatis-plus:
  #配置Mapper映射文件
  mapper-locations: classpath*:com/sishui/words/mapper/**/*.xml
  # 配置MyBatis数据返回类型别名（默认别名是类名）
  type-aliases-package: com.sishui.words.pojo
## Mybatis SQL 打印(方法接口所在的包，不是Mapper.xml所在的包)
logging:
  level:
    com.sishui.words.mapper: debug